import type { NextPage } from 'next'
import { GetStaticProps } from 'next'
import { createClient } from 'contentful';
import Head from 'next/head'
import Link from 'next/link';
import { useState } from 'react';
import Posts from './Posts/allPosts';
import Title from './Title'
import Nav from './components/Nav';

export const getStaticProps: GetStaticProps = async () => {
  const client = createClient({
    space: 'gd4ogqr6qlta',
    accessToken: 'ce9ONNNwgGamg2qITKzoG4SToVs1ilv68jQUFustLX0',
  })

  const contentfulContent = await client.getEntries({ content_type: 'blog' })

  return {
    props: { data: contentfulContent.items }
  }
}

const Home: NextPage = ({ data }: any) => {
  const [title, setTitle] = useState('title');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen w-screen bg-gradient-to-r from-yellow-500 from-orange-500 to-pink-500 bg-cover'>
        <Nav />
        <h1 className='text-3xl font-bold uppercase text-center'>Home Page</h1>
        {data.map((res: any) => (
          <div id={res.fields.id} className="grid justify-center">
            <h2 className='text-2xl'>Entry: {res.fields.name}</h2>
            <img src={`${res.fields.thumbnail}`} alt="me" />
            <h2>{res.fields.date}</h2>
          </div>
        ))}

      </div>
    </>
  )
}

export default Home;
